import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';

import '../constants/app_constants.dart';
import '../../features/season/data/models/season_model.dart';
import '../../features/plot/data/models/plot_model.dart';
import '../../features/activity/data/models/activity_model.dart';
import '../../features/reminder/data/models/reminder_model.dart';
import '../../features/analytics/data/models/revenue_model.dart';

/// Helper that initialises Hive and opens all required boxes.
///
/// Call [HiveHelper.init] once in [main] before [runApp].
/// Access boxes anywhere via static getters without re-opening them.
class HiveHelper {
  HiveHelper._();

  static late Box<dynamic> _prefsBox;

  /// Opens all Hive boxes the app needs.
  static Future<void> init() async {
    if (kIsWeb) {
      // Hive works in-browser without a path.
      await Hive.initFlutter();
    } else {
      final appDocDir = await getApplicationDocumentsDirectory();
      await Hive.initFlutter(appDocDir.path);
    }

    // Register type adapters (generated by hive_generator)
    Hive.registerAdapter(SeasonModelAdapter());
    Hive.registerAdapter(PlotModelAdapter());
    Hive.registerAdapter(ActivityModelAdapter());
    Hive.registerAdapter(ReminderModelAdapter());
    Hive.registerAdapter(RevenueModelAdapter());

    // Open boxes
    _prefsBox = await Hive.openBox<dynamic>(AppConstants.prefsBox);
    await Hive.openBox<dynamic>(AppConstants.farmersBox);
    await Hive.openBox<SeasonModel>('seasons');
    await Hive.openBox<PlotModel>('plots');
    await Hive.openBox<ActivityModel>('activities');
    await Hive.openBox<ReminderModel>('reminders');
    await Hive.openBox<RevenueModel>('revenues');
  }

  /// User preferences box (locale, theme choice, etc.)
  static Box<dynamic> get prefsBox => _prefsBox;

  /// Convenience: read a preference value.
  static T? getPref<T>(String key) => _prefsBox.get(key) as T?;

  /// Convenience: write a preference value.
  static Future<void> setPref<T>(String key, T value) =>
      _prefsBox.put(key, value);

  /// Close all boxes and Hive.
  static Future<void> close() async {
    await Hive.close();
  }

  /// Delete all data (use with caution).
  static Future<void> clearAllData() async {
    await Hive.box<SeasonModel>('seasons').clear();
    // Clear other boxes as needed
  }
}
